### PR TITLE
Add Jenkins to community contributions

### PR DESCRIPTION
**Pull request by justinharringa**

### CODE REVIEW

**Comment by justinharringa** [comment]
I also pulled in a better Raft image

**Comment by jamesward** [comment]
Might be window width since we use media queries to adjust for mobile.  Which is super fun to test.  :)

**Comment by justinharringa** [comment]
Yeah, that appears to be part of the problem. I was able to reproduce locally too.

**Comment by justinharringa** [comment]
So looks like I can get us here: 

image

**Comment by jamesward** [comment]
Maybe @interactivellama can get it the rest of the way.  :)

**Comment by interactivellama** [comment]
I'll look at it this week. Can I have rights to push to Justin's branch, please? @jamesward

**Comment by justinharringa** [comment]
I guess I kind of went with the main model that seems to be in place in case other icons are going to get added. The main issue seems to be that the Raft icon is just the circle (well, k8s falls into that as well but has the luxury of being on the right in this instance). 

This turns out to be the worst view of it.

**Comment by justinharringa** [comment]
I added you to the team @interactivellama 😄

**Comment by interactivellama** [comment]
@jamesward Updated to:

screen shot 2018-05-03 at 10 08 33 am

**Comment by justinharringa** [comment]
Nice @interactivellama! I had tried to snag some images with names but couldn't find anything for raft. LGTM

**Comment by interactivellama** [comment]
I just ended up making it in Illustrator

**Comment by jamesward** [comment]
Awesome!  Thanks all.

**Pull request merged**
