### PR TITLE
Make project logos bigger and in two rows

### PR DESCRIPTION
**Pull request by interactivellama**
For "built at" section:
* Convert table to float layout so that images wrap to next line
* Prevent floats at small screen widths
* Add DSR logo to page

### See screenshots below:
Wide
screen shot 2018-03-20 at 1 16 02 am

narrow
screen shot 2018-03-20 at 9 20 43 am

### CODE REVIEW

**Comment by interactivellama** [comment]
screen shot 2018-03-20 at 9 40 46 am

**Comment by interactivellama** [comment]
@jamesward Ready for review. 🎉

**Comment by jamesward** [comment]
Check out the review app: https://salesforce-github-io-pr-14.herokuapp.com/

**Comment by interactivellama** [comment]
Looks like x-large screen sizes cause overflow. I will look into.

**Pull request merged**
