### PR TITLE
Fetch recent posts from medium.com

### PR DESCRIPTION
**Pull request by ongardie-sfdc**
The static ones on the page are already stale.

Check it out on: https://ongardie-sfdc.github.io/salesforce.github.io/

### CODE REVIEW

**Comment by ongardie-sfdc** [comment]
Err, hold off on this, I think there might be a race condition in here.

**Comment by ongardie-sfdc** [comment]
Ok, fixed that, ready for your consideration now.

/cc @demianbrecht

**Comment by ongardie-sfdc** [comment]
Seems to work well on Chrome, Firefox, Safari desktop and Chrome and Safari mobile. Firefox on Android uses a suboptimal date format ("3/23/2016") but otherwise works.

**Comment by demianbrecht** [comment]
Rather than having the static list in there at all, can you replace it with loading text, with a link to the blog for cases where the script breaks?

**Comment by ongardie-sfdc** [comment]
@demianbrecht What about taking it one step farther and removing the recent posts box by default? If the script breaks, they won't know they're missing out, and there's already a link to Medium at the top of the page.

**Comment by demianbrecht** [comment]
Yeah that works for me

**Comment by ongardie-sfdc** [comment]
@demianbrecht updated

**Comment by demianbrecht** [comment]
What about using mustache or similar for rendering content? IIRC it increases readability, is minimal overhead, is available via cdnjs and sets the stage for inclusion of other API responses if we chose to add them. Not a merge blocker but might be nice to use that from the get go instead of raw element manipulation.

**Comment by ongardie-sfdc** [comment]
@demianbrecht I'm inclined to leave it using DOM for now. I don't want this little piece of code adding a dependency on mustache (or anything else) in case this project ends up pulling in an equivalent but different dependency later for some bigger feature.

**Comment by demianbrecht** [comment]
Sure sounds good

**Comment by ongardie-sfdc** [comment]
Plus es6 template strings will be usable on here one day :)

**Pull request merged**
